name: Indexer Image

on:
  push:
    branches: [master]
    tags: ["v*"]
    paths:
      - ".github/workflows/indexer-image.yml"
      - "indexer/**"
  pull_request:
    paths:
      - ".github/workflows/indexer-image.yml"
      - "indexer/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build indexer image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}-indexer" >> "$GITHUB_ENV"

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v6
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha,prefix=sha-

      - uses: docker/build-push-action@v7.2.0
        with:
          context: indexer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
